-- Blog entries are stored in Supabase; the public portfolio CMS uses the
-- same anon-key write model as the existing cases and other_projects tables.
create table if not exists public.articles (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  excerpt text not null default '',
  content text not null default '',
  cover_image text not null default '',
  cover_alt text not null default '',
  seo_title text not null default '',
  meta_description text not null default '',
  canonical_override text not null default '',
  noindex boolean not null default false,
  og_title text not null default '',
  og_description text not null default '',
  og_image text not null default '',
  author text not null default 'Ксения Матвеенко',
  category text not null default 'Статья',
  tags text[] not null default '{}',
  status text not null default 'draft' check (status in ('draft', 'published')),
  published_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  reading_time text not null default '5 мин'
);

create index if not exists articles_status_published_at_idx
  on public.articles (status, published_at desc);

alter table public.articles enable row level security;
grant select, insert, update, delete on public.articles to anon, authenticated;
grant usage, select on sequence public.articles_id_seq to anon, authenticated;

create policy "Public read articles"
  on public.articles for select to anon, authenticated using (true);
create policy "Public insert articles"
  on public.articles for insert to anon, authenticated with check (true);
create policy "Public update articles"
  on public.articles for update to anon, authenticated using (true) with check (true);
create policy "Public delete articles"
  on public.articles for delete to anon, authenticated using (true);
